version: '2'
services:
    web:
        image: nginx:latest
        container_name: alpena_web_nginx
        ports:
            - "8000:80"
            - "8010:443"
        restart: always
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./web:/web"
        depends_on:
            - "php"
            - "mysqldb"
    php:
        image: nanoninja/php-fpm
        container_name: alpena_web_php
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - ./web:/web
    composer:
        image: composer/composer
        container_name: alpena_web_composer
        restart: always
        volumes:
            - ./web/app:/app
        command: install
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: alpena_web_phpmyadmin
        ports:
            - "8020:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
        restart: always
        depends_on:
            - "mysqldb"
    mysqldb:
        image: mysql
        container_name: alpena_web_mysql
        restart: always
        environment:
            - MYSQL_DATABASE=test
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=dev
            - MYSQL_PASSWORD=dev
        ports:
            - 3306:3306
        volumes:
            - ./data/db/mysql:/var/lib/mysql
    master:
        image: redis:3
        container_name: alpena_web_redis_master
        restart: always
    slave_1:
        image: redis:3
        container_name: alpena_web_redis_slave_1
        restart: always
        command: redis-server --slaveof redis-master 6379
        links:
            - master:redis-master
    slave_2:
        image: redis:3
        container_name: alpena_web_redis_slave_2
        restart: always
        command: redis-server --slaveof redis-master 6379
        links:
            - master:redis-master